# Generated by Django 4.2.6 on 2024-04-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('idPayRates', models.AutoField(primary_key=True, serialize=False)),
                ('PayRateName', models.CharField(max_length=255)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PayType', models.IntegerField()),
                ('PayAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PTLevelC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_payrate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.payrate')),
            ],
            options={
                'ordering': ['idPayRates'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idEmployee', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeNumber', models.IntegerField(unique=True)),
                ('LastName', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('SSN', models.DecimalField(decimal_places=0, max_digits=9)),
                ('PayRate', models.CharField(blank=True, max_length=255)),
                ('VacationDays', models.IntegerField(blank=True, null=True)),
                ('PaidToDate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PayRates_idPay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.payrate')),
            ],
            options={
                'ordering': ['LastName', 'FirstName'],
            },
        ),
    ]
