# Generated by Django 5.0.4 on 2024-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PaidLastYear',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
