# Generated by Django 4.2.6 on 2024-04-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('MappingID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.groups')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
    ]
