# Generated by Django 4.2.6 on 2024-04-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='GroupID',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
