# Generated by Django 4.2.6 on 2024-04-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=50, null=True)),
                ('Deductable', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Percentage_CoPay', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emergency_Contact_Name', models.CharField(max_length=50, null=True)),
                ('Phone_Number', models.CharField(max_length=50, null=True)),
                ('Relationship', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employment_Status', models.CharField(max_length=50, null=True)),
                ('Hire_Date', models.DateTimeField(null=True)),
                ('Workers_Comp_Code', models.CharField(max_length=50, null=True)),
                ('Termination_Date', models.DateTimeField(null=True)),
                ('Rehire_Date', models.DateTimeField(null=True)),
                ('Last_Review_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50, null=True)),
                ('Division', models.CharField(max_length=50, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
                ('Job_Title', models.CharField(max_length=50, null=True)),
                ('Supervisor', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Job_Category', models.CharField(max_length=50, null=True)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('Departmen_Code', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Salary_Type', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Pay_Period', models.CharField(max_length=50, null=True)),
                ('Hours_per_Week', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Hazardous_Training', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationHistory',
            fields=[
                ('MigrationId', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('ContextKey', models.CharField(max_length=300)),
                ('Model', models.BinaryField()),
                ('ProductVersion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('Employee_ID', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Middle_Initial', models.CharField(max_length=50, null=True)),
                ('Address1', models.CharField(max_length=50, null=True)),
                ('Address2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Zip', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Phone_Number', models.CharField(max_length=50, null=True)),
                ('Social_Security_Number', models.CharField(max_length=50, null=True)),
                ('Drivers_License', models.CharField(max_length=50, null=True)),
                ('Marital_Status', models.CharField(max_length=50, null=True)),
                ('Gender', models.BooleanField(null=True)),
                ('Shareholder_Status', models.BooleanField()),
                ('Ethnicity', models.CharField(max_length=50, null=True)),
                ('Benefit_Plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to='hr_app.benefit_plans')),
            ],
        ),
        migrations.AddConstraint(
            model_name='migrationhistory',
            constraint=models.UniqueConstraint(fields=('MigrationId', 'ContextKey'), name='PK_dbo.__MigrationHistory'),
        ),
        migrations.AddField(
            model_name='job_history',
            name='job_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.personal'),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.personal'),
        ),
        migrations.AddField(
            model_name='employment',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hr_app.personal'),
        ),
        migrations.AddField(
            model_name='emergency_contacts',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts_employee', to='hr_app.personal'),
        ),
        migrations.AddField(
            model_name='emergency_contacts',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts_personal', to='hr_app.personal'),
        ),
    ]
