# Generated by Django 5.0.4 on 2024-04-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_alter_jobhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitplans',
            options={'ordering': ['BENEFIT_PLANS_ID']},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ['EMPLOYMENT_ID']},
        ),
        migrations.AlterModelOptions(
            name='employmentworkingtime',
            options={'ordering': ['EMPLOYMENT_WORKING_TIME_ID']},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['PERSONAL_ID']},
        ),
    ]
